#### Publish to docker hub 
name: Build and deploy Ubuntu base images
on:
  push:
    branches:
    - master
    paths:
      - '.github/workflows/base_ubuntu.yml'
      - 'docker/base/os/ubuntu/Dockerfile.jammy'
  workflow_dispatch:

jobs:
  deploy:
    name: Checkout and deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/build-push-action@v4
        with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_TOKEN }}
            repository: thevlang/vlang
            tags: ubuntu-base
            dockerfile: ${{github.workspace}}/docker/base/os/ubuntu/Dockerfile.jammy
