#### Publish to docker hub 
name: Build and deploy Alpine base images
on:
  push:
    branches:
    - master
    paths:
      - '.github/workflows/base_alpine.yml'
      - 'docker/base/os/alpine/Dockerfile.alpine'
  workflow_dispatch:

env:
  PLATFORMS: linux/amd64,linux/arm64

jobs:
  deploy:
    name: Checkout and deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_TOKEN }}
      - uses: docker/build-push-action@v4
        with:
            platforms: ${{ env.PLATFORMS}}
            tags: ${{ secrets.DOCKER_USERNAME }}/vlang:base-alpine
            push: true
            file: docker/base/os/alpine/Dockerfile.alpine
