#### Publish to docker hub 
name: Build and deploy All base images
on:
  push:
    branches:
    - master
    - feature/matrixing
    paths:
      - '.github/workflows/base.yml'
      - 'docker/base/Dockerfile.alpine'
      - 'docker/base/Dockerfile.debian'
  workflow_dispatch:

env:
  PLATFORMS: ${{ vars.PLATFORMS }}

jobs:
  deploy:
    name: Checkout and deploy
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        os:
          - alpine
          - debian
    steps:
      - uses: actions/checkout@v1
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_TOKEN }}
      - uses: docker/build-push-action@v4
        with:
            platforms: ${{ env.PLATFORMS}}
            tags: ${{ secrets.DOCKER_USERNAME }}/vlang:base-${{ matrix.os }}
            push: true
            file: docker/base/Dockerfile.${{ matrix.os }}
            build-args: "USER=${{secrets.DOCKER_USERNAME}}"
