#### Publish to docker hub
name: Build and deploy Ubuntu builder image
on:
  push:
    branches:
    - master
    paths:
      - '.github/workflows/build_ubuntu.yml'
      - 'docker/vlang/Dockerfile.ubuntu.build'
  workflow_dispatch:

jobs:
  deploy:
    name: Checkout and deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/build-push-action@v4
        with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_TOKEN }}
            repository: thevlang/vlang
            tags: ubuntu-build
            dockerfile: ${{github.workspace}}/docker/vlang/Dockerfile.ubuntu.build
