#### Publish to docker hub
name: Build and deploy All builder image
on:
  push:
    branches:
    - master
    pull_request:
      branches: [master] 
    paths:
      - '.github/workflows/build.yml'
      - 'docker/vlang/Dockerfile.alpine.build'
      - 'docker/vlang/Dockerfile.debian.build'
  workflow_dispatch:

jobs:
  deploy:
    name: Checkout and deploy
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        os:
          - alpine
          - debian
    steps:
      - uses: actions/checkout@v1
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_TOKEN }}
      - uses: docker/build-push-action@v4
        with:
            platforms: ${{ vars.PLATFORMS}}
            tags: ${{ vars.DOCKER_REPOSITORY }}/vlang:${{ matrix.os}}-build
            push: ${{ github.event_name != 'pull_request' }}
            file: docker/vlang/Dockerfile.${{ matrix.os }}.build
            build-args: "USER=${{vars.DOCKER_REPOSITORY}}"
