#### Publish to docker hub 
name: Build and deploy all
on:
  push:
    branches:
    - main
    paths:
      - '.github/workflows/matrix-docker.yml'
      - 'docker/base/os/alpine/Dockerfile.alpine'
      - 'docker/base/os/alpine/Dockerfile.debian'
      - 'docker/base/os/alpine/Dockerfile.ubuntu'
      - 'docker/vlang/Dockerfile.alpine'
      - 'docker/vlang/Dockerfile.debian'
      - 'docker/vlang/Dockerfile.ubuntu'
  workflow_dispatch:

jobs:
  deploy:
    name: Checkout and deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: 
          #- alpine
          - debian
          #- ubuntu
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v2
        with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_TOKEN }}
      - uses: docker/build-push-action@v4
        name: base-${{matrix.os}}
        with:
            platforms: ${{ env.PLATFORMS}}
            tags: ${{ secrets.DOCKER_USERNAME }}/vlang:base-${{ matrix.os }}
            push: true
            file: docker/base/os/${{matrix.os}}/Dockerfile.${{ matrix.os }}
            build-args: "USER=${{secrets.DOCKER_USERNAME}}"
      - uses: docker/build-push-action@v4
        name: ${{matrix.os}}-build
        with:
            platforms: ${{ env.PLATFORMS}}
            tags: ${{ secrets.DOCKER_USERNAME }}/vlang:${{ matrix.os }}-build
            push: true
            file: docker/vlang/Dockerfile.${{ matrix.os}}
            build-args: "USER=${{secrets.DOCKER_USERNAME}}"
