#### Publish tags to docker hub
name: Deploy nightly build to Dockerhub
on:
  workflow_dispatch:
  # for manually trigger workflow
  push:
    branches:
      - master
    paths:
      - ".github/workflows/nightly_builds.yml"
  schedule:
    - cron: "0 2 * * *" # run at 2 AM UTC

env:
  PLATFORMS: ${{ vars.PLATFORMS }}

jobs:
  deploy_latest:
    name: Checkout and deploy
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        os:
          - alpine
          - debian
    steps:
      - uses: actions/checkout@v1
      - uses: docker/build-push-action@v1
        name: Build and deploy Alpine
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
          repository: thevlang/vlang
          tags: ${{ matrix.os }}
          dockerfile: ${{github.workspace}}/docker/vlang/Dockerfile.${{ matrix.os }}
      - uses: docker/build-push-action@v1
        name: Build and deploy developer build Alpine
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
          repository: thevlang/vlang
          tags: ${{ matrix.os }}-dev
          dockerfile: ${{github.workspace}}/docker/vlang/Dockerfile.${{ matrix.os }}.dev-full
