#### Publish tags to docker hub
name: Deploy nightly build to Dockerhub
on:
  workflow_dispatch:
  # for manually trigger workflow
  push:
    branches:
      - master
    paths:
      - ".github/workflows/nightly_builds.yml"
  schedule:
    - cron: "0 2 * * *" # run at 2 AM UTC

jobs:
  deploy_latest:
    name: Checkout and deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/build-push-action@v4
        name: Build and deploy Alpine latest
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
          repository: thevlang/vlang
          tags: alpine
          dockerfile: ${{github.workspace}}/docker/vlang/Dockerfile.alpine
      - uses: docker/build-push-action@v4
        name: Build and deploy Debian latest
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
          repository: thevlang/vlang
          tags: latest, debian
          dockerfile: ${{github.workspace}}/docker/vlang/Dockerfile.debian
      - uses: docker/build-push-action@v4
        name: Build and deploy Ubuntu latest
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
          repository: thevlang/vlang
          tags: ubuntu
          dockerfile: ${{github.workspace}}/docker/vlang/Dockerfile.ubuntu
      - uses: docker/build-push-action@v4
        name: Build and deploy developer build Alpine
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
          repository: thevlang/vlang
          tags: alpine-dev
          dockerfile: ${{github.workspace}}/docker/vlang/Dockerfile.alpine.dev-full
      - uses: docker/build-push-action@v4
        name: Build and deploy developer build Debian
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
          repository: thevlang/vlang
          tags: debian-dev
          dockerfile: ${{github.workspace}}/docker/vlang/Dockerfile.debian.dev-full
      - uses: docker/build-push-action@v4
        name: Build and deploy developer build Ubuntu
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
          repository: thevlang/vlang
          tags: ubuntu-dev
          dockerfile: ${{github.workspace}}/docker/vlang/Dockerfile.ubuntu.dev-full
