#### Publish tags to docker hub
name: Deploy nightly build to Dockerhub
on:
  workflow_dispatch:
  # for manually trigger workflow
  push:
    branches:
      - master
    paths:
      - ".github/workflows/nightly_builds.yml"
  schedule:
    - cron: "0 2 * * *" # run at 2 AM UTC

jobs:
  deploy_latest:
    name: Checkout and deploy
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        os:
          - alpine
          - debian
    steps:
      - uses: actions/checkout@v1
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_TOKEN }}
      - uses: docker/build-push-action@v4
        name: Build and deploy v image
        with:
          platforms: ${{ vars.PLATFORMS }}
          tags: ${{ vars.DOCKER_REPOSITORY }}/vlang:${{ matrix.os }}
          file: docker/vlang/Dockerfile.${{ matrix.os }}
          push: true
          build-args: "USER=${{vars.DOCKER_REPOSITORY}}"
      - uses: docker/build-push-action@v4
        name: Build and deploy developer build
        with:
          platforms: ${{ vars.PLATFORMS }}
          tags: ${{ vars.DOCKER_REPOSITORY }}/vlang:${{ matrix.os }}-dev
          file: docker/vlang/Dockerfile.${{ matrix.os }}.dev-full
          build-args: "USER=${{vars.DOCKER_REPOSITORY}}"
