#### Publish tags to docker hub
name: Deploy nightly build to Dockerhub
on:
  workflow_dispatch:
  # for manually trigger workflow
  push:
    branches:
      - master
    paths:
      - ".github/workflows/nightly_builds.yml"
  schedule:
    - cron: "0 2 * * *" # run at 2 AM UTC

jobs:
  deploy_latest:
    name: Checkout and deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/build-push-action@v4
        name: Build and deploy Alpine
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
          repository: thevlang/vlang
          tags: alpine
          dockerfile: ${{github.workspace}}/docker/vlang/Dockerfile.alpine
      - uses: docker/build-push-action@v4
        name: Build and deploy Debian Bullseye
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
          repository: thevlang/vlang
          tags: latest, bullseye
          dockerfile: ${{github.workspace}}/docker/vlang/Dockerfile.bullseye
      - uses: docker/build-push-action@v4
        name: Build and deploy Ubuntu Focal
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
          repository: thevlang/vlang
          tags: latest, bullseye
          dockerfile: ${{github.workspace}}/docker/vlang/Dockerfile.ubuntu
      - uses: docker/build-push-action@v4
        name: Build and deploy developer build Alpine
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
          repository: thevlang/vlang
          tags: alpine-dev
          dockerfile: ${{github.workspace}}/docker/vlang/Dockerfile.alpine.dev-full
      - uses: docker/build-push-action@v4
        name: Build and deploy developer build Debian Bullseye
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
          repository: thevlang/vlang
          tags: bullseye-dev
          dockerfile: ${{github.workspace}}/docker/vlang/Dockerfile.bullseye.dev-full
      - uses: docker/build-push-action@v4
        name: Build and deploy developer build Ubuntu Focal
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
          repository: thevlang/vlang
          tags: bullseye-dev
          dockerfile: ${{github.workspace}}/docker/vlang/Dockerfile.ubuntu.dev-full
